### ISSUE TITLE
caniuse_local breaks on load

### ISSUE THREAD

**Issue by stephanfriedrich** [leecade/caniuse_local#5]
Reloading plugin /home/friedrich/.config/sublime-text-2/Packages/caniuse_local/v8.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./v8.py", line 11, in <module>
    import SublimeJS.loader.pyv8loader as pyv8loader
ImportError: No module named SublimeJS.loader.pyv8loader

**Comment by leecade** [comment]
This plugin require pyv8, if auto installed failed try [Manual installation](https://github.com/emmetio/pyv8-binaries#manual-installation)

and load issue see https://github.com/sergeche/emmet-sublime/issues/129

**Comment by LOQUILLO** [comment]
I had installed pyv8 manually but nothing has changed, there are the error, dont show nothing in status bar
